language: minimal

script: 
  - docker build -t linksmart/deployment-ui --label "travis_buildNumber=$TRAVIS_BUILD_NUMBER" .
  
before_deploy: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 

deploy:
  - provider: script
    script: docker push linksmart/deployment-ui
    on:
      branch: master
